[package]
name = "quad-timestamp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
 
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
chrono = "0.4"